GitHub auth
saradrada/workshop-api-testing-js pull request #5
Opened 2020-12-11 15:56 UTC by saradrada

2020-12-11 16:01 UTC, leonleo997 commented on test/GithubApi.Gist.test.js
> +        expect(gist).to.exist;
can you add more expectations?

2020-12-11 16:02 UTC, leonleo997 commented on test/GithubApi.Gist.test.js
> +        const response = await agent
instead of assign it to `response`, you can assign it to `gist`

2020-12-11 16:03 UTC, leonleo997 commented on test/GithubApi.Gist.test.js
> +        gist = response;
once you assign it to gist, you can delete this line

2020-12-11 16:04 UTC, leonleo997 commented on test/GithubApi.Put.test.js
> +        .auth('token', process.env.ACCESS_TOKEN); // For rate limiting
delete comment

2020-12-11 16:04 UTC, leonleo997 commented on test/GithubApi.Put.test.js
> +    it(`When we check we're actually following ${githubUserName}'s github account`, () => {
is this a When or a Then?

2020-12-11 16:06 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
>        // runs once before all the test in a describe
delete comment

2020-12-11 16:06 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it(`When we check if contains the ${repositoryName} repository`, () => {
is this a when or a then?

2020-12-11 16:08 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +        expect(repoAsZip.status).to.equal(statusCode.OK);
can you improve this verification step? can you add an additional way to see that the file is downloaded successfully?

2020-12-11 16:08 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it('When we check the md5 of the README.file', () => {
is this a when or a then?

2020-12-11 16:08 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it('When we check the md5 of the README.file', () => {
add more assertions

2020-12-11 16:09 UTC, leonleo997 commented on test/GithubApi.Issue.test.js
> +    it('When we check the user has at least 1 public repository', () => {
is this a when or a then?

2020-12-11 16:10 UTC, leonleo997 commented on test/GithubApi.Issue.test.js
> +      repositoryName = repo.name;
why are you assign a value to this variable?

2020-12-11 16:11 UTC, leonleo997 commented on test/GithubApi.Issue.test.js
> +    it('When we create an issue', () => {
is this a when or a then?

2020-12-11 16:11 UTC, leonleo997 commented on test/GithubApi.Issue.test.js
> +    it('When we modify an issue', () => {
is this a when or a then?

2020-12-11 16:11 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it('When we check the name, path and sha of the README.md file', () => {
is this a when or a then?

2020-12-11 16:52 UTC, leonleo997 commented
If you want to encourage the challenge, I would like that you can create a reusable class where you assign the base URL and the agent b/c you always have to assign them

2020-12-14 13:43 UTC, saradrada commented on test/GithubApi.Issue.test.js
> +      repositoryName = repo.name;
I need the information (name) of a specific repository to create an issue.

2020-12-14 15:50 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
>        // runs once before all the test in a describe
@saradrada

2020-12-14 15:50 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it(`When we check if contains the ${repositoryName} repository`, () => {
@saradrada

2020-12-14 15:50 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it('When we check the md5 of the README.file', () => {
@saradrada

2020-12-14 20:54 UTC, leonleo997 commented on test/GithubApi.Put.test.js
> +/* const chai = require('chai');
delete this

2020-12-14 20:54 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +      it('The the name, path and sha of the README.md file are the expected', () => {
Then*

2020-12-14 20:54 UTC, leonleo997 commented on test/GithubApi.Config.js
> +exports.getStatusCode = () => statusCode;
revert changes

2020-12-14 20:54 UTC, leonleo997 commented on test/GithubApi.Config.js
> +exports.getAgent = () => agent;
revert changes

2020-12-15 15:26 UTC, leonleo997 requested changes

2020-12-15 15:26 UTC, leonleo997 commented on test/GithubApi.Authentication.test.js
>  const agent = require('superagent');
delete this dependency. It is not needed

2020-12-15 15:26 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +          const response = await agent
change this to request

2020-12-15 15:26 UTC, leonleo997 commented on test/GithubApi.Repositories.test.js
> +const agent = require('superagent');
delete this dependency. It is not needed

2020-12-15 15:26 UTC, leonleo997 commented on test/MyFirstApiConsume.test.js
> +const agent = require('superagent');
delete this dependency. It is not needed

2020-12-15 15:26 UTC, leonleo997 commented on test/MyFirstApiConsume.test.js
> +  const response = await agent
change to request

2020-12-15 15:26 UTC, leonleo997 commented on test/MyFirstApiConsume.test.js
> +  const response = await agent
change to request

2020-12-15 15:35 UTC, saradrada commented on test/GithubApi.Authentication.test.js
>  const agent = require('superagent');
I need the dependency because of the request that sends the tokens by parameters

2020-12-15 21:19 UTC, saradrada commented on test/MyFirstApiConsume.test.js
> +const agent = require('superagent');
I need it for the patch request with query parameters

2020-12-15 22:20 UTC, leonleo997 commented
Great work 👏

2020-12-15 22:20 UTC, leonleo997 approved these changes

2020-12-15 22:25 UTC, merged